#!/bin/sh
### BEGIN INIT INFO
# Provides:          proxy
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the SDMdata server.
### END INIT INFO

case "$1" in
start)
    start-stop-daemon --start --background --exec /home/demo_user/SDMdata/sdmdata/web_server.py
;;
stop)
    start-stop-daemon --stop --name web_server.py
esac
